package bootstrap

// Code generated by `zatrano db:setup`. DO NOT edit by hand unless you know why.
// Re-run: go run ./cmd/zatrano db:setup --drivers=...
import (
	_ "github.com/zatrano/framework/packages/database/driver/sqlite"
)
