package bootstrap

// Code generated by `zatrano db:setup`. DO NOT edit by hand unless you know why.
// No database drivers linked by default. Re-run:
//
//	go run ./cmd/zatrano db:setup --drivers=sqlite,mysql,pgsql
