package console

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/zatrano/framework/v2/kernel"
)

func registerAgentsCommand(console *Application, app *kernel.Application) {
	_ = app
	console.Register(&AgentsGenerateCommand{})
}

// AgentsGenerateCommand writes AGENTS.md from the live describe document.
type AgentsGenerateCommand struct {
	out io.Writer
}

func (c *AgentsGenerateCommand) Name() string { return "agents:generate" }
func (c *AgentsGenerateCommand) Description() string {
	return "Generate AGENTS.md from zatrano describe (do not edit the file by hand)"
}

func (c *AgentsGenerateCommand) writer() io.Writer {
	if c.out != nil {
		return c.out
	}
	return os.Stdout
}

func (c *AgentsGenerateCommand) Handle(args []string) error {
	if hasFlag(args, "--help", "-h") {
		fmt.Fprintln(c.writer(), "Usage: zatrano agents:generate [path]")
		return nil
	}
	root, err := os.Getwd()
	if err != nil {
		return err
	}
	for _, a := range args {
		if strings.HasPrefix(a, "-") {
			continue
		}
		root = a
		break
	}
	path, err := WriteAgentsMarkdown(root)
	if err != nil {
		return err
	}
	fmt.Fprintf(c.writer(), "Wrote %s\n", path)
	return nil
}

// WriteAgentsMarkdown renders describe output into root/AGENTS.md.
func WriteAgentsMarkdown(root string) (string, error) {
	abs, err := filepath.Abs(root)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(abs, 0o755); err != nil {
		return "", err
	}
	doc, err := BuildDescribeDocument(abs)
	if err != nil {
		return "", err
	}
	body := RenderAgentsMarkdown(doc)
	path := filepath.Join(abs, "AGENTS.md")
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

// RenderAgentsMarkdown turns a describe document into AGENTS.md (deterministic).
func RenderAgentsMarkdown(doc *DescribeDocument) string {
	if doc == nil {
		return ""
	}
	var b strings.Builder
	b.WriteString("# AGENTS.md\n\n")
	fmt.Fprintf(&b, "Generated by `zatrano agents:generate` from `zatrano describe` (framework %s). Re-run after upgrading the framework. Do not edit by hand.\n\n", doc.Version)

	b.WriteString("## Routing\n\n")
	b.WriteString("HTTP routes are registered with these primitives (parsed from `kernel/routing/discovery.go`):\n\n")
	for _, m := range doc.Routing.Primitives {
		fmt.Fprintf(&b, "- `%s`\n", m.Signature)
	}
	b.WriteString("\n")
	if dirs := routeLayoutDirs(); len(dirs) > 0 {
		b.WriteString("Put `RegisterWeb` / `RegisterAPI` in:\n\n")
		for _, d := range dirs {
			fmt.Fprintf(&b, "- `%s/`\n", d)
		}
		b.WriteString("\n")
	}
	b.WriteString("`ApplyWeb` and `ApplyAPI` run from an application `Provider` under `app/providers` (typically `RouteServiceProvider`).\n\n")
	if len(doc.Routing.SampleRoutes) > 0 {
		b.WriteString("Sample route-registration calls in this project:\n\n")
		for _, r := range doc.Routing.SampleRoutes {
			fmt.Fprintf(&b, "- `%s:%d` `%s`", r.File, r.Line, r.Call)
			if r.Path != "" {
				fmt.Fprintf(&b, " `%s`", r.Path)
			}
			if r.Group != "" {
				fmt.Fprintf(&b, " (%s)", r.Group)
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	b.WriteString("## Config and providers\n\n")
	p := doc.Providers.Interface
	fmt.Fprintf(&b, "Application providers implement `%s` (`%s`):\n\n", p.Name, p.File)
	for _, m := range p.Methods {
		fmt.Fprintf(&b, "- `%s`\n", m.Signature)
	}
	sr := doc.Providers.SelfRegistration
	b.WriteString("\nAddon self-registration (parsed from `bootstrap/addons`):\n\n")
	fmt.Fprintf(&b, "- package: `%s`\n", sr.Package)
	fmt.Fprintf(&b, "- Register: `%s`\n", sr.Register)
	fmt.Fprintf(&b, "- Select: `%s`\n", sr.Select)
	fmt.Fprintf(&b, "- Lookup: `%s`\n", sr.Lookup)
	fmt.Fprintf(&b, "- Available: `%s`\n", sr.Available)
	fmt.Fprintf(&b, "- Meta: `%s` fields `%s`\n", sr.MetaType, strings.Join(sr.MetaFields, ", "))
	fmt.Fprintf(&b, "- Meta.%s: `%s`\n", sr.FactoryField, sr.FactoryReturns)
	fmt.Fprintf(&b, "- register_called_from: `%s`\n", sr.RegisterCalledFrom)
	fmt.Fprintf(&b, "- registry_imports_addons: `%t`\n", sr.RegistryImportsAddons)
	fmt.Fprintf(&b, "- consumer_blank_import: `%t`\n", sr.ConsumerBlankImport)
	b.WriteString("\nAddon config maps belong in the addon's own Provider, not in kernel boot. Load application settings through `contracts.ConfigRepository` (`Application.Config()`).\n\n")

	b.WriteString("## Catalog\n\n")
	for _, layer := range doc.Catalog.Layers {
		fmt.Fprintf(&b, "### `%s` (`%s`)\n\n", layer.Constant, layer.Name)
		if layer.Role != "" {
			fmt.Fprintf(&b, "%s\n\n", layer.Role)
		}
		for _, pkg := range layer.Packages {
			fmt.Fprintf(&b, "- `%s` [%s]", pkg.Name, pkg.Kind)
			if pkg.Heavy {
				b.WriteString(" heavy")
			}
			if pkg.Description != "" {
				fmt.Fprintf(&b, " — %s", pkg.Description)
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	b.WriteString("## Contracts\n\n")
	b.WriteString("Prefer these interfaces over concrete `packages/` types. Direct imports of contract concretes are reported by `zatrano doctor` (check `concrete`).\n\n")
	names := make([]string, 0, len(doc.Contracts))
	for name := range doc.Contracts {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		ct := doc.Contracts[name]
		fmt.Fprintf(&b, "### `%s` (`%s`)\n\n", ct.Name, ct.File)
		for _, m := range ct.Methods {
			fmt.Fprintf(&b, "- `%s`\n", m.Signature)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Doctor\n\n")
	b.WriteString("Run `zatrano doctor` from an application root (`app/` present). It reports warnings (not build errors) for:\n\n")
	for _, check := range DoctorChecks() {
		fmt.Fprintf(&b, "- `%s`\n", check.Name)
	}
	b.WriteString("\nEach finding includes **found**, **why**, and **how** to fix. There is no `--fix` flag.\n")
	return b.String()
}

func routeLayoutDirs() []string {
	dirs, err := requiredStarterAppDirs()
	if err != nil {
		return nil
	}
	var out []string
	for _, d := range dirs {
		if strings.Contains(d, "routes/") || strings.HasSuffix(d, "routes") {
			out = append(out, d)
		}
	}
	return out
}
